services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - PORT=8000
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - "8000:8000"
        command: >
            sh -c "npx prisma migrate deploy && npx prisma generate && node dist/src/app.js"

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        restart: unless-stopped
        environment:
            - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        ports:
            - "3000:3000"
        depends_on:
            - api

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt:ro
        depends_on:
            - api
            - frontend

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: ["/bin/sh", "-c"]
        command: >
            "certbot certonly --webroot -w /var/www/certbot
            --force-renewal --email ${EMAIL}
            -d ${FRONTEND_DOMAIN} -d ${FRONTEND_DOMAIN_WWW}
            -d ${BACKEND_DOMAIN} -d ${BACKEND_DOMAIN_WWW}
            --agree-tos --non-interactive
            && certbot renew --quiet"
