version: "3.8"

services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - PORT=8000
            - DATABASE_URL=postgresql://edstock_db_owner:fG1b8snClgzu@ep-royal-thunder-a1f8psgf.ap-southeast-1.aws.neon.tech/edstock_db?sslmode=require
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_BASE_URL: http://api.edstock.live
        restart: unless-stopped
        environment:
            - NEXT_PUBLIC_API_BASE_URL=http://api.edstock.live
        ports:
            - "3000:3000"
        depends_on:
            - api

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt:ro
        depends_on:
            - api
            - frontend

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: ["/bin/sh", "-c"]
        command: >
            "certbot certonly --webroot -w /var/www/certbot
            --force-renewal --email korngsamnang168@gmail.com
            -d edstock.live -d www.edstock.live -d api.edstock.live -d www.api.edstock.live
            --agree-tos --non-interactive
            && certbot renew --quiet"
