name: edstock-app

services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - PORT=${PORT}
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - "8000:8000"
        networks:
            - app-network

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL} # Pass as build arg
        restart: unless-stopped
        environment:
            - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL} # Also pass it as runtime env
        ports:
            - "3000:3000"
        depends_on:
            - api
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
            - frontend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
