name: edstock-app

services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - PORT=8000
            - DATABASE_URL=postgresql://edstock_db_owner:fG1b8snClgzu@ep-royal-thunder-a1f8psgf.ap-southeast-1.aws.neon.tech/edstock_db?sslmode=require
        ports:
            - "8000:8000"
        networks:
            - app-network
        deploy:
            replicas: 2

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_BASE_URL: http://api.edstock.live # Pass as build arg
        restart: unless-stopped
        environment:
            - NEXT_PUBLIC_API_BASE_URL=http://api.edstock.live # Pass as runtime env
        ports:
            - "3000:3000"
        depends_on:
            - api
        networks:
            - app-network
        deploy:
            replicas: 2

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
            - frontend
        networks:
            - app-network
        deploy:
            replicas: 1

networks:
    app-network:
        driver: overlay
